version: '3'

services:
  express-ts:
    build:
      context: .
      dockerfile: Dockerfile
    image: express-ts-service
    container_name: express-ts-service
    restart: unless-stopped
    ports:
      - "1234:1234"
    environment:
      - NODE_ENV=production
      - SERVICE_PORT=1234

